from selenium import webdriver 
import time 
wd = webdriver.Chrome('/Users/liutaige/Downloads/chromedriver')

wd.get("http://localhost:8080")
wd.maximize_window()

time.sleep(2)

# # login as Admin 
# wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
# time.sleep(2)

# #Sending message "0000" to klaus
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[4]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div[2]/div[2]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul/li[2]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('//*[@id="Target"]').send_keys('klaus')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div/textarea').send_keys('0000')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div[2]/div[2]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
# time.sleep(2)

# # login as klaus
# wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('klaus')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
# time.sleep(2)

# #Sending message "1111" to Admin
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[4]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div[3]/div[2]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul/li[2]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('//*[@id="Target"]').send_keys('Admin')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div/textarea').send_keys('1111')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div/div[3]/div[2]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
# time.sleep(2)

# # login as Admin 
# wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
# time.sleep(2)

# # testing changing password correctly 1
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[2]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[1]/div[2]/input').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[2]/div[2]/input').send_keys('654321')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[3]/div[2]/input').send_keys('654321')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
# time.sleep(2)

# # testing login again
# wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
# time.sleep(2)

# a1 = wd.switch_to.alert
# time.sleep(2)
# a1.accept()

# wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('654321')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
# time.sleep(2)

# #testing changing password incorrectly
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[2]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[1]/div[2]/input').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[2]/div[2]/input').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[3]/div[2]/input').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/input').click()
# time.sleep(2)

# #changing back password
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[2]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[1]/div[2]/input').send_keys('654321')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[2]/div[2]/input').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[3]/div[2]/input').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
# time.sleep(2)

# # login as Admin 
# wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
# time.sleep(2)

# # Going to "Posts" and click "first test"
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[3]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[1]/input').click()
# time.sleep(2)

# #testing different types of comment in Forum 
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[1]').send_keys('1111')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[2]').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[1]').send_keys('1a1a')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[2]').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[1]').send_keys('Hello world!!')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[2]').click()
# time.sleep(2)

# #Testing creating new post 
# wd.find_element_by_xpath('/html/body/div[2]/div[2]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('//*[@id="title"]').send_keys('testing new post')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div/div[2]/div[2]/div[2]/select').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div/div[2]/div[2]/div[2]/select/option[5]').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div/div[2]/textarea').send_keys('Random content ...')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/form/div/div[2]/input').click()
# time.sleep(2)

# #Checking new post 
# wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[3]/a').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[2]/form/div[11]/div[1]/input').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[1]').send_keys('1111')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[2]').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[1]').send_keys('1a1a')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[2]').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[1]').send_keys('Hello world!!')
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[2]/div[1]/form/div/div/input[2]').click()
# time.sleep(2)
# wd.find_element_by_xpath('/html/body/div[1]/ul/li[3]/a').click()
# time.sleep(2)

# #Testing deleting new post 
# wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[2]/form/div[10]/div[3]/input').click()
# time.sleep(2)
# a1 = wd.switch_to.alert
# time.sleep(2)
# a1.accept()

# login as Admin 
wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
time.sleep(2)

#Testing Modify rules (adding new normal user)
wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[5]/a').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div[3]/input').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[1]/div[2]/input').send_keys('normal1')
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[2]/div[2]/input').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[3]/div[2]/input').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[4]/div[2]/select').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[4]/div[2]/select/option[1]').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/input').click()
time.sleep(2)
a1 = wd.switch_to.alert
time.sleep(2)
a1.accept()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[1]/ul/li[5]/a').click()
time.sleep(2)


#Testing Modify rules (adding new admin user)
wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[5]/a').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div[3]/input').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[1]/div[2]/input').send_keys('admin1')
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[2]/div[2]/input').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[3]/div[2]/input').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[4]/div[2]/select').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/div[4]/div[2]/select/option[2]').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/div[2]/input').click()
time.sleep(2)
a1 = wd.switch_to.alert
time.sleep(2)
a1.accept()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
time.sleep(2)

#login as normal1
wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('normal1')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[1]/a').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
time.sleep(2)

#login as admin1
wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('admin1')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[1]/a').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[1]/ul/li[4]/a').click()
time.sleep(2)

# login as Admin 
wd.find_element_by_xpath('/html/body/form/div[1]/input[1]').send_keys('Admin')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/input[2]').send_keys('123456')
time.sleep(2)
wd.find_element_by_xpath('/html/body/form/div[1]/button').click()
time.sleep(2)

#Deleting new added users
wd.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[5]/a').click()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div[2]/div[9]/input[1]').click()
time.sleep(2)
a1 = wd.switch_to.alert
time.sleep(2)
a1.accept()
time.sleep(2)
wd.find_element_by_xpath('/html/body/div[2]/div/div[2]/form/div[2]/div[8]/input[1]').click()
time.sleep(2)
a1 = wd.switch_to.alert
time.sleep(2)
a1.accept()
time.sleep(2)

